### ISSUE TITLE
Discord has changed ordering in the chat for usernames/timestamps, leading to awkward placement of pronouns.

### ISSUE THREAD

**Issue by SmolAlli** [Penguin-Spy/powercord-ppl-moe#8]
**Describe the bug**
Discord has changed ordering in the chat for usernames/timestamps, leading to awkward placement of pronouns. See images below
Expected:
![image](https://user-images.githubusercontent.com/22519967/171988031-260e52a9-b293-4706-85ef-a84803995afc.png)
Actual:
![image](https://user-images.githubusercontent.com/22519967/171988058-91100d45-51b1-4d79-887a-516c3f9034b8.png)

**To Reproduce**
1. Look at a person in chat who has a pronoun added to their name.

**Other**
I made a temporary fix via CSS, it makes the header area flex and then orders the elements. Will probably mess up the order of other elements if there is something else that adds into the chat.
```css
.cozy-VmLDNB .header-2jRmjb { display: flex; }
.header-2jRmjb .headerText-2z4IhQ { order: 0; }
.header-2jRmjb  .ppl-moe-pronouns { order: 2; }
.header-2jRmjb  .timestamp-p1Df1m.timestampInline-_lS3aK { order: 1; }
```
